# -*- coding: utf-8 -*-
"""kalkulator_spldv2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZocHte-TVro3OC19CcA1MZULePG3Fw8G
"""

import streamlit as st

def solve_spldv_substitusi_streamlit(a1, b1, c1, a2, b2, c2):
    st.markdown("### Memulai Perhitungan")
    st.info(f"Persamaan 1: **{a1}x + {b1}y = {c1}**")
    st.info(f"Persamaan 2: **{a2}x + {b2}y = {c2}**")

    st.markdown("---")
    st.markdown("### Langkah 1: Ubah salah satu persamaan")
    st.write("Kita akan mencoba mengubah Persamaan 1 untuk menyatakan `x` dalam bentuk `y`.")

    substitute_var = ''
    m_val = 0
    c_val = 0

    if a1 == 0:
        st.warning("Koefisien A1 adalah 0. Tidak bisa menyatakan x dari Persamaan 1 dengan mudah.")
        st.write("Mari kita coba menyatakan `y` dari Persamaan 1: $y = (c_1 - a_1x) / b_1$")
        if b1 == 0:
            st.error("Kedua koefisien A1 dan B1 adalah 0. Persamaan 1 tidak valid sebagai persamaan linear.")
            st.error("Tidak dapat melanjutkan. Harap periksa input Anda.")
            return None, None # Mengembalikan None jika tidak bisa dilanjutkan

        substitute_var = 'y'
        m_val = -a1 / b1
        c_val = c1 / b1
        st.code(f"y = ({c1} - {a1}x) / {b1}")
        st.success(f"Jadi, y = {m_val:.2f}x + {c_val:.2f}")

    else:
        substitute_var = 'x'
        m_val = -b1 / a1
        c_val = c1 / a1
        st.code(f"x = ({c1} - {b1}y) / {a1}")
        st.success(f"Jadi, x = {m_val:.2f}y + {c_val:.2f}")

    st.markdown("---")
    st.markdown("### Langkah 2 & 3: Substitusi dan Selesaikan")
    st.write(f"Sekarang, kita akan substitusikan ekspresi untuk **{substitute_var}** ke Persamaan 2.")

    x_solution = None
    y_solution = None

    if substitute_var == 'x':
        # Substitusi x = (c1 - b1*y) / a1 ke a2*x + b2*y = c2
        # a2 * ((c1 - b1*y) / a1) + b2*y = c2
        # y * (b2 - (a2*b1 / a1)) = c2 - (a2*c1 / a1)
        denominator = (b2 * a1 - a2 * b1)
        if abs(denominator) < 1e-9: # Mendekati nol untuk floating point
            st.error("Determinan sistem mendekati nol. Sistem ini mungkin tidak memiliki solusi unik (sejajar atau berhimpit).")
            return None, None

        numerator_y = (c2 * a1 - a2 * c1)
        y_solution = numerator_y / denominator
        st.markdown(f"""
        Setelah substitusi $x = \\frac{{{c1} - {b1}y}}{{{a1}}}$ ke persamaan 2:
        $ {a2} \\left( \\frac{{{c1} - {b1}y}}{{{a1}}} \\right) + {b2}y = {c2} $
        """)
        st.code(f"y * ({b2} * {a1} - {a2} * {b1}) = ({c2} * {a1} - {a2} * {c1})")
        st.code(f"y * ({denominator:.2f}) = ({numerator_y:.2f})")
        st.success(f"Maka, **y = {y_solution:.2f}**")
        x_solution = (c1 - b1 * y_solution) / a1

    else: # substitute_var == 'y'
        # Substitusi y = (c1 - a1*x) / b1 ke a2*x + b2*y = c2
        # a2*x + b2 * ((c1 - a1*x) / b1) = c2
        # x * (a2 - (b2*a1 / b1)) = c2 - (b2*c1 / b1)
        denominator = (a2 * b1 - b2 * a1)
        if abs(denominator) < 1e-9: # Mendekati nol untuk floating point
            st.error("Determinan sistem mendekati nol. Sistem ini mungkin tidak memiliki solusi unik (sejajar atau berhimpit).")
            return None, None

        numerator_x = (c2 * b1 - b2 * c1)
        x_solution = numerator_x / denominator
        st.markdown(f"""
        Setelah substitusi $y = \\frac{{{c1} - {a1}x}}{{{b1}}}$ ke persamaan 2:
        $ {a2}x + {b2} \\left( \\frac{{{c1} - {a1}x}}{{{b1}}} \\right) = {c2} $
        """)
        st.code(f"x * ({a2} * {b1} - {b2} * {a1}) = ({c2} * {b1} - {b2} * {c1})")
        st.code(f"x * ({denominator:.2f}) = ({numerator_x:.2f})")
        st.success(f"Maka, **x = {x_solution:.2f}**")
        y_solution = (c1 - a1 * x_solution) / b1

    st.markdown("---")
    st.markdown("### Langkah 4: Substitusi Balik")
    st.write(f"Setelah kita menemukan {'y' if substitute_var == 'x' else 'x'} = { (y_solution if substitute_var == 'x' else x_solution):.2f},")
    st.write("kita akan substitusikan nilai ini kembali ke Persamaan 1 untuk menemukan nilai variabel yang tersisa.")

    if substitute_var == 'x':
        if abs(b1) < 1e-9:
            st.error("Koefisien B1 adalah 0. Tidak dapat menemukan y dari Persamaan 1.")
            return None, None
        calculated_y = (c1 - (a1 * x_solution)) / b1
        st.code(f"{a1} * {x_solution:.2f} + {b1}y = {c1}")
        st.code(f"{a1 * x_solution:.2f} + {b1}y = {c1}")
        st.code(f"{b1}y = {c1} - {a1 * x_solution:.2f}")
        st.code(f"{b1}y = {c1 - (a1 * x_solution):.2f}")
        st.code(f"y = {(c1 - (a1 * x_solution)):.2f} / {b1:.2f}")
        st.success(f"Didapatkan **y = {calculated_y:.2f}**")
        y_final = calculated_y
        x_final = x_solution
    else: # substitute_var == 'y'
        if abs(a1) < 1e-9:
            st.error("Koefisien A1 adalah 0. Tidak dapat menemukan x dari Persamaan 1.")
            return None, None
        calculated_x = (c1 - (b1 * y_solution)) / a1
        st.code(f"{a1}x + {b1} * {y_solution:.2f} = {c1}")
        st.code(f"{a1}x + {b1 * y_solution:.2f} = {c1}")
        st.code(f"{a1}x = {c1} - {b1 * y_solution:.2f}")
        st.code(f"{a1}x = {c1 - (b1 * y_solution):.2f}")
        st.code(f"x = {(c1 - (b1 * y_solution)):.2f} / {a1:.2f}")
        st.success(f"Didapatkan **x = {calculated_x:.2f}**")
        x_final = calculated_x
        y_final = y_solution

    return x_final, y_final

# --- Tampilan Antarmuka Streamlit ---
st.set_page_config(
    page_title="Kalkulator SPLDV Substitusi",
    page_icon="🔢",
    layout="centered",
    initial_sidebar_state="expanded"
)

st.title("🔢 Kalkulator SPLDV")
st.subheader("Menyelesaikan Sistem Persamaan Linear Dua Variabel dengan Metode Substitusi")

st.markdown("""
Aplikasi ini akan memandu Anda menyelesaikan SPLDV (Sistem Persamaan Linear Dua Variabel)
menggunakan **Metode Substitusi** secara interaktif.
Masukkan koefisien untuk kedua persamaan Anda dalam format:
$Ax + By = C$
""")

st.markdown("---")
st.markdown("### Masukkan Persamaan Anda")

col1, col2 = st.columns(2)

with col1:
    st.markdown("#### Persamaan 1 ($A_1x + B_1y = C_1$)")
    a1 = st.number_input("Koefisien $A_1$", value=2.0, key="a1")
    b1 = st.number_input("Koefisien $B_1$", value=1.0, key="b1")
    c1 = st.number_input("Konstanta $C_1$", value=5.0, key="c1")

with col2:
    st.markdown("#### Persamaan 2 ($A_2x + B_2y = C_2$)")
    a2 = st.number_input("Koefisien $A_2$", value=3.0, key="a2")
    b2 = st.number_input("Koefisien $B_2$", value=-2.0, key="b2")
    c2 = st.number_input("Konstanta $C_2$", value=4.0, key="c2")

st.markdown("---")

if st.button("Hitung Solusi", type="primary"):
    st.markdown("## Proses Penyelesaian")
    with st.expander("Lihat Langkah-langkah Detail", expanded=True):
        x_final, y_final = solve_spldv_substitusi_streamlit(a1, b1, c1, a2, b2, c2)

    if x_final is not None and y_final is not None:
        st.markdown("---")
        st.markdown("## 🎉 Solusi Akhir 🎉")
        st.success(f"Nilai **x = {x_final:.2f}**")
        st.success(f"Nilai **y = {y_final:.2f}**")

        st.markdown("---")
        st.markdown("### Verifikasi Solusi")
        check1 = a1 * x_final + b1 * y_final
        check2 = a2 * x_final + b2 * y_final
        st.markdown(f"**Persamaan 1**: `{a1} * {x_final:.2f} + {b1} * {y_final:.2f} = {check1:.2f}` (Seharusnya `{c1:.2f}`)")
        st.markdown(f"**Persamaan 2**: `{a2} * {x_final:.2f} + {b2} * {y_final:.2f} = {check2:.2f}` (Seharusnya `{c2:.2f}`)")

        if abs(check1 - c1) < 1e-6 and abs(check2 - c2) < 1e-6: # Toleransi kecil untuk floating point
            st.balloons()
            st.success("🎉 Solusi Anda TEPAT! 🎉")
        else:
            st.warning("Ada sedikit perbedaan dalam verifikasi. Mungkin karena pembulatan, atau ada kasus khusus.")